[package]
name = "passkey-hd-wallet"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
bip32 = "0.5"
ed25519-dalek = "2.0"
webauthn-rs = "0.4"
serde = { version = "1.0", features = ["derive"] }
blake3 = "1.5"
openssl = { version = "0.10", features = ["vendored"] }
openssl-sys v0.9.104

[dev-dependencies]
proptest = "1.0"