[package]
name = "wallet_passkey"
version = "0.1.0"
edition = "2021"

[dependencies]
# Bitcoin and HD wallet dependencies
bitcoin = "0.29"
bip39 = "2.0"
bip32 = "0.5"
bitcoin_hashes = "0.11"

openssl-sys = "0.9.105"  # or a newer version
openssl = "0.10"         # optional, for a higher-level interface

# Serialization and JSON
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Web and async
tokio = { version = "1.0", features = ["full"] }
warp = "0.3"

# Authentication
webauthn-rs = "0.3"

# Error handling and utilities
thiserror = "1.0"
tracing = "0.1"
hex = "0.4"
ring = "0.16"
